name: cubes
description: Simple State Manager (Focusing on simplicity and rebuilding only the necessary)
version: 1.0.0-nullsafety.0
homepage: https://github.com/RafaelBarbosatec/cube

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^5.0.6


dev_dependencies:
  mockito: any
  effective_dart: any
  flutter_test:
    sdk: flutter

flutter:

