name: cubes
description: Simple State Manager (Focusing on rebuilding only the necessary)
version: 0.3.4
homepage: https://github.com/RafaelBarbosatec/cube

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

